# The Bar && Font && Font size (11)
i: /usr/local/share/wbar/osxbarback.png
t: /usr/local/lib/X11/fonts/TTF/luxisr/11
c: wbar -bpress -pos bottom -zoomf 2 -isize 32

i: /usr/local/share/pixmaps/aterm.png
t: Terminal
c: aterm

i: /usr/local/share/pixmaps/pcmanfm.png
t: Files
c: pcmanfm

i: /usr/local/share/icons/hicolor/16x16/apps/leafpad.png
t: Text Editor
c: leafpad

i: /usr/local/share/pixmaps/geany.png
t: Code Editor
c: geany

i: /usr/local/share/pixmaps/gpicview.png
t: Image Viewer
c: gpicview

i: /usr/local/share/pixmaps/mtpaint.png
t: Paint
c: mtpaint

i: /usr/local/share/icons/hicolor/48x48/apps/galculator.png
t: Calculator
c: galculator

i: /usr/local/share/icons/hicolor/16x16/apps/abiword.png
t: Word Processor
c: abiword

i: /usr/local/share/icons/hicolor/16x16/apps/midori.png
t: Web Browser
c: midori

i: /usr/local/share/pixmaps/uzdoom.png
t: Doom
c: uzdoom
