Section "Module"
    Load "extmod"
    Load "glx"
EndSection

Section "Files"
    FontPath "/usr/share/fonts/X11/misc"
    FontPath "/usr/share/fonts/X11/Type1"
    FontPath "/usr/share/fonts/truetype/liberation"
    ModulePath "/usr/local/lib/xorg/modules"
EndSection

Section "ServerFlags"
    Option "AutoAddDevices" "true"
    Option "AutoEnableDevices" "true"
EndSection

Section "Monitor"
    Identifier "My Monitor"
    HorizSync 31.5 - 50.0
    VertRefresh 40-90
EndSection

Section "Device"
    Identifier "VESA Framebuffer"
    Driver "vesa"
    Option "ShadowFB" "true"
EndSection

Section "Screen"
    Identifier "Screen 1"
    Device "VESA Framebuffer"
    Monitor "My Monitor"
    DefaultDepth 24
    Subsection "Display"
        Depth 24
        Modes "1024x768" "800x600"
    EndSubsection
EndSection

Section "ServerLayout"
    Identifier "Simple Layout"
    Screen "Screen 1"
EndSection
